### ISSUE TITLE
Before you Get Started

### ISSUE THREAD

**Issue by thovo** [letientai299/google-interview-university#1]
I will work into this section from now. Should we have another task tracking to easy view the progress?

**Comment by letientai299** [comment]
Check out this: https://github.com/letientai299/google-interview-university/projects/1
It's should be easy to track the progress. 
BTW, this is the first time I try Gihub's Project 😃

**Comment by thovo** [comment]
#

**Comment by thovo** [comment]
#2

**Comment by thovo** [comment]
Refer to PR #2

**Comment by letientai299** [comment]
Merged. Also remove the Github Project, because its complex is not worth for our small project.

**Comment by letientai299** [comment]
You may want to add your name and contact information as the top of the translation :smile:

**Comment by thovo** [comment]
Okay, almost forgot this part :joy:
