### ISSUE TITLE
Some translation issues

### ISSUE THREAD

**Issue by dangkhoasdc** [letientai299/google-interview-university#11]
I haven't forked your repo yet. I've just skim your translation and found some minor errors and confused terms:

- [x] `hay việc duyệt đồ thị (graph)`. It should be `graph traversal` [Link](https://en.wikipedia.org/wiki/Graph_traversal).
- [x] trong dời (typo) -> trong đời.
- [x] hàng ngàn mảng liên kết (map hoặc dictionary cho dễ hiểu). `mảng liên kết` is a confused term. People used to think it is a `linked list` or a `doubly linked list` and `map` or `dict` are different terms, underneath there are symbol table, implemented by binary tree or hashing table. In [soha.vn](http://tratu.soha.vn/dict/en_vn/Array), they call it `mảng kết hợp`. I think it doesn't make more sense than 'mảng liên kết`, but it is less confused than the other.
- [x] Search (tên sản phảm của Google): `Trình tìm kiếm` or `công cụ tìm kiếm`.
- [x] cốn sách  -> cuốn sách.
- [x] Sedgewick. Anh ta rất xuất sắc. FYI, Sedgewick is a famous CS professor and is a student of Don Knuth. `Anh ta` isn't suitable for the context. 
- [x] Phân tích biên độ -> Phân tích tiệm cận 
- [x] con trỏ toán -> phép toán con trỏ.
- [x] triển khai . It should be `cấp phát`, right? 
- [x] nhưng chúng thường được lưu trữ theo kiểu tuyến tính (mảng, danh sách liên kết). Priority Queue and Binary heap are implemented by tree, as I remembered.

**Comment by letientai299** [comment]
Thanks for review and suggestion. Would be nice if the issues are linked with line or place I can found it in the document. 

Agree on all the typo issues. 

About Sedgewick, I don't know John's age, just assume that from his perspective, "Anh ta" (same age level) is OK. But we can change to "Ong ay" hoac "Thay ay". @thovo, @dangkhoasdc, how to you think?

Search, I just want to keep this English name. That's how they call it. And for their other products (Youtube, Inbox, Translate, ...) we cannot translate them into our language anyway.

PR are welcomed.

**Comment by dangkhoasdc** [comment]
Sedgewick is almost 70 years old. He definitely is older than John :smile: 

About the name "Search", I think it's ok for the heading. However, in the title of some videos it should be translated into "Trình tìm kiếm".

**Comment by letientai299** [comment]
Ok. I'll update that.

**Comment by thovo** [comment]
@dangkhoasdc : Normally, I translated directly from what John wrote in his README.md
Let look again this part:
Phân tích biên độ -> Phân tích tiệm cận -> I agree it would be better :smile: in John's origin: Asymptotic analysis --> just don't remember what my professor said in university.
 con trỏ toán -> phép toán con trỏ. -> it is more suitable for VNese students
 triển khai . It should be cấp phát, right? --> agree :smile: 
 nhưng chúng thường được lưu trữ theo kiểu tuyến tính (mảng, danh sách liên kết). Priority Queue and Binary heap are implemented by tree, as I remembered. --> this part is direct translation from John, we may double check with John or raise a new issue to let him know

**Comment by thovo** [comment]
It would be better if we take part in two roles: translator and reviewer. We may swap the role each week to share the workload. It also helps to improve the translation.

**Comment by dangkhoasdc** [comment]
@thovo About the `associate array` term, I think John uses the term correctly. The problem is only in Vietnamese, I think that we don't have a suitable word in our language for that.

**Comment by letientai299** [comment]
@dangkhoasdc  That's the issue. Hence, I suggest to add translator note and leave it as English when you feel it's hard to explain the term. Translator note can be put as a quote (see "Sử dụng như thế nào").

**Comment by thovo** [comment]
Many terms don't have corresponding word in Vietnamese or our knowledge about Vietnamese characters is not well enough :joy: It is better in some case we leave the English and add an explanation in Vietnamese to demonstrate what the word is about.

By example:

> insert(index, value) - insert value at index, so current item at that index is pointed to by new item at index

The repeating of `index` may cause confused for reader so in the translation I added some example to illustrate what happens.

> insert(index, value) - Thêm giá trị mới tại vị trí chỉ mục, dữ liệu hiện tại sẽ trỏ về dữ liệu mới tại vị trí chỉ mục này (A->B->C, thêm N tại vị trí B, A->D->B->C, A hiện giờ sẽ trỏ tới D, chỉ mục 1 sẽ trỏ tới D thay vì B)

Add some code to demonstrate would be better.

In the end, this translation is for Vietnamese, we should do our best to help people understand the concept than plain non-sense translation

**Comment by dangkhoasdc** [comment]
@thovo great ideas :+1:

**Comment by dangkhoasdc** [comment]
@letientai299 @thovo  Let's me check the current version and update typo as translation issues of each sections in order to review. You guys can continue translating in other sections.

**Comment by dangkhoasdc** [comment]
I've fixed overall typo and change some words that I had mentioned before.
