### ISSUE TITLE
Sync with latest update in your repos from my fork repo

### ISSUE THREAD

**Issue by thovo** [letientai299/google-interview-university#14]
Hi, I would like to know how I will get update from yours safely?
Currently, after I worked around manually with several commands, it worked but I am not sure it would be the right way, so please advise!

My command list:

```bash
git remote -v
upstream        https://github.com/letientai299/google-interview-university.git (fetch)
upstream        https://github.com/letientai299/google-interview-university.git (push)
```

```bash
git rebase upstream/vietnamese
```

And usually lead to some rebase conflict that need me to solve it manually. So I change to this command:

```bash
git fetch -u --force upstream vietnamese:vietnamese
```

And discard all my changes to the files with `git checkout -- .` to get update with the newest.

**Comment by thovo** [comment]
It would be a temporary solution, I think we should consider a better approach :smile:

**Comment by letientai299** [comment]
Close since there's lacking of activity here.
