### ISSUE TITLE
Pick System Design, Scalability, Data Handling

### ISSUE THREAD

**Issue by thovo** [letientai299/google-interview-university#17]
@letientai299 : It should be easier if we marked the missing section as task, and pickup from that? I recommend we use Trello to arrange task easily

**Comment by letientai299** [comment]
Each section tooks about 30 minutes to 1 hour for continuously working, so I don't pre-create issues and additional tool like Trello worth it. I also don't want to make current workflow become more complex. It would be hard for new contributror to get started in.

Anyway, I'm still open for other ideas and improvements on our workflow. 

cc @dangkhoasdc for your thinking.

**Comment by dangkhoasdc** [comment]
Hi, I think we should do as simple as possible. You guys can pick sections, create an issue and translate and after that I can review and check typo :smile: 

We can divide contributors into 2 groups: translators and reviewers. 

For instant, now I don't have time to translate but it is doable for me to review your work.

**Comment by thovo** [comment]
Okay, KISS :smile: 
Anw, there is some words really hard to find the same corresponding word in VNese, or I need to write a complete article in VNese to explain the word, what do you think in this case? I leave as is now.

By example:

> Google's Transition From Single Datacenter, To Failover, To A Native Multihomed Architecture

> Failover: a method of protecting computer systems from failure, in which standby equipment automatically takes over when the main system fails.

> Native Multihomed Architecture: No idea

I need to read the article to understand what it really means but I assume at first it is a way of expressing that Google now can translate many different languages at native level

**Comment by letientai299** [comment]
> I leave as is now.

Agree. Also, you could raise an issue to discuss on how should we deal with a specific term.

**Comment by thovo** [comment]
In some case, author left only one word like this

>  Spanner - The link is http://highscalability.com/blog/2012/9/24/google-spanners-most-surprising-revelation-nosql-is-out-and.html

Spanner by itself mean the expand in size as I suppose, but the real article may refer differently

**Comment by letientai299** [comment]
First time I heard about Spanner (didn't read till that section :smile:). After [some](https://research.google.com/archive/spanner.html) [research](https://en.wikipedia.org/wiki/Spanner_(database)), it's seems Spanner is a Google product, so it's fine to leave it as English.

**Comment by letientai299** [comment]
Close this since the section has been translated. For further discussion, please raise another issue.
