### ISSUE TITLE
Sorting&Graph: typo and confusing terms

### ISSUE THREAD

**Issue by dangkhoasdc** [letientai299/google-interview-university#19]
Here is the list of confusing terms:

- [ ] `sắp xếp ổn định` - stable sort.
- [x] `quicksort` should be `quicksort`.

I will update the list later.

**Comment by thovo** [comment]
> From Wiki: A sorting algorithm is said to be stable if two objects with equal keys appear in the same order in sorted output as they appear in the input unsorted array. Some sorting algorithms are stable by nature like Insertion sort, Merge Sort, Bubble Sort, etc.


So I think the `stable` here means the order of the same keys keeps reserved in new sorted array. We may keep the English word and explain like this: `Sắp xếp nhưng không thay đổi trật tự trước đó của các khóa có cùng giá trị`. This is not a different sort algorithm, just an adj.

**Comment by dangkhoasdc** [comment]
Yes, I mean we should translate the term so that people think that is a property of a sort algorithms rather than a specific algorithm.

I will close the issue for further editing.
