### ISSUE TITLE
Pick Coding Question Practice

### ISSUE THREAD

**Issue by thovo** [letientai299/google-interview-university#27]
Link for this part: [Coding Question Practice](https://github.com/thovo/google-interview-university#coding-question-practice)

In my previous pull, I think you missed this part [Process and Threads](https://github.com/thovo/google-interview-university#processes-and-threads ), could you please merge it, @letientai299 ?

**Comment by letientai299** [comment]
Thank for your reminder. That part had been done by @dauruy, but I forget to rearrange after merging your PR.

**Comment by letientai299** [comment]
Hi. I've made some changes to address the missing part. Be sure to backup your work before pulling.

**Comment by letientai299** [comment]
Done in #31
